### ISSUE TITLE
Enemies are rotated/rotate incorrectly when tracking the player.

### ISSUE THREAD

**Issue by rowlandsc** [bi3mer/gmap377_leathGloves_inc#117]

**Comment by rawhat** [comment]
The new rotation functionality has fixed this problem.

For future reference:
-  `Vector3.LookAt` takes an option parameter for an `up` vector.  If not provided, it uses the `worldUp` vector, and rotates the `GameObject` so that its `Transform.up` is equal to the `worldUp` vector.  This was causing the strange rotations.
