### ISSUE TITLE
Animated Plane for water

### ISSUE THREAD

**Issue by mrod9000** [bi3mer/gmap377_leathGloves_inc#247]
Basically we need an animated plane with triangulated ripples see video:

https://www.youtube.com/watch?v=K4oideCI6UU

We're going to use it for water.

**Comment by insanity180** [comment]
no good idea just yet on how to do this, gonna keep researching. The linked video is like a cool video but no tutorial

**Comment by insanity180** [comment]
Gonna have to do Cody's suggestion of animating the vectors, I did a lot of research trying to find a better alternative but I see none. I wanted to avoid this since I can't rig (well at least, I guess I could) the
 water to react so I am a bit scared on doing this, but vector based animation is possible but messy.

**Comment by mrod9000** [comment]
lolololol goodbye
